<?php
/**
 * Story Meta dynamic block renderer.
 *
 * Reuses the established csco_get_post_meta() rendering contract so the block
 * inherits the current Vaarta/Caards visual language during migration.
 *
 * @package Vaarta
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$post_id = get_the_ID();
if ( ! $post_id || ! function_exists( 'csco_get_post_meta' ) ) {
	return;
}

$allowed_items = array(
	'category',
	'author',
	'date',
	'comments',
	'views',
	'shares',
	'reading_time',
);

$items = isset( $attributes['items'] ) && is_array( $attributes['items'] )
	? array_values( array_intersect( $attributes['items'], $allowed_items ) )
	: array( 'category', 'author', 'date', 'comments', 'reading_time' );

if ( ! $items ) {
	return;
}

$compact       = ! empty( $attributes['compact'] );
$author_avatar = ! empty( $attributes['authorAvatar'] );

$markup = csco_get_post_meta(
	$items,
	$compact,
	false,
	$items,
	array(
		'author_avatar' => $author_avatar,
		'container'     => true,
	)
);

if ( ! $markup ) {
	return;
}

$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => 'vaarta-story-meta',
	)
);
?>
<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by core. ?>>
	<?php echo wp_kses_post( $markup ); ?>
</div>
